---
# PersistentVolume - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwdc-nfs-pv-db
  labels:
    volume: gwdc-nfs-volume-db
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 10.8.41.12
    path: "/mnt/sharedfolder/gwdc/wordpress/db/"
---
# PersistentVolumeClaim - NFS
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-db
  namespace: gwdc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: gwdc-nfs-volume-db
  storageClassName: ""
---
# db
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwdc-db
  namespace: gwdc
  labels:
    name: gwdc-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gwdc-db
  template:
    metadata:
      labels:
        name: gwdc-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - name: port-mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: config
              key: WORDPRESS_DB_NAME
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: config
              key: WORDPRESS_DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config
              key: WORDPRESS_DB_PASSWORD
        resources: {}
        volumeMounts:
          - name: nfs-mysql-data
            mountPath: "/var/lib/mysql"
      volumes:
      - name: nfs-mysql-data
        persistentVolumeClaim:
          claimName: nfs-pvc-db
---
# mysql service
apiVersion: v1
kind: Service
metadata:
  name: gwdc-db
  namespace: gwdc
  labels:
    name: gwdc-db
spec:
  ports:
  - name: gwdc-db
    port: 3306
    targetPort: 3306
  selector:
    name: gwdc-db
...
