---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: vault-agent
  name: wordpress
rules:
  - apiGroups: ["*"]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["secrets"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-rolebinding
  labels:
    app: vault-agent
subjects:
  - kind: ServiceAccount
    name: wordpress 
    namespace: gwdc
roleRef:
  kind: Role
  name: wordpress
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress
  namespace: gwdc