---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: gwdc
  name: secrets-integrator-wordpress
  namespace: gwdc
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-pre-populate-only : "true"
            vault.hashicorp.com/agent-inject-secret-config.yaml: kv/gwdc/wordpress
            vault.hashicorp.com/agent-inject-template-config.yaml: |
              {{- with secret "kv/gwdc/wordpress" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              data:
                {{ range $k, $v := .Data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: gwdc
                name: config
              {{- end }}
            vault.hashicorp.com/role: wordpress
        spec:
          containers:
            - name: gwdc-vault-kube-integrator
              image: "bitnami/kubectl:1.17.4"
              imagePullPolicy: "IfNotPresent"
              command:
                - kubectl
                - apply
                - "-f"
                - /vault/secrets/
              resources: {}
          imagePullSecrets: []
          restartPolicy: Never
          serviceAccountName: wordpress
