---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gwdc-ing
  namespace: gwdc
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: gwdc.org.au
    http:
      paths:
      - backend:
          service:
            name: gwdc-web
            port: 
              number: 80
        pathType: Prefix
...