apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: gwdc
  name: secrets-integrator-gwdc
  namespace: gwdc
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-init-first: 'true'
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-secret-gwdc.wordpress.yaml: gwdc/kv/wordpress
            vault.hashicorp.com/agent-inject-template-gwdc.wordpress.yaml: |
              {{- with secret "gwdc/kv/wordpress" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              stringData:
                {{ range $k, $v := .Data.data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: gwdc
                name: wordpress
              {{- end }}
            vault.hashicorp.com/agent-pre-populate-only: 'true'
            vault.hashicorp.com/role: gwdc
        spec:
          containers:
            - command:
                - kubectl
                - apply
                - '-f'
                - /vault/secrets/
              image: 'bitnami/kubectl:1.17.4'
              imagePullPolicy: IfNotPresent
              name: vault-kube-integrator
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: gwdc
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
