---
# PersistentVolume - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwdc-nfs-pv-app
  labels:
    volume: gwdc-nfs-volume-app
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 10.8.41.12
    path: "/mnt/sharedfolder/gwdc/wordpress/app"
...
