---
# PersistentVolume - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwdc-nfs-pv-app
  labels:
    volume: gwdc-nfs-volume-app
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 10.8.0.37
    path: "/mnt/sharedfolder/gwdc/wp_html"
...
