---
# PersistentVolumeClaim - NFS
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-app
  namespace: gwdc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: gwdc-nfs-volume-app
...
