---
# webapp deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwdc-web
  namespace: gwdc
  labels:
    name: gwdc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gwdc-web
  template:
      labels:
        name: gwdc-web
    spec:
      containers:
        - name: gwdc-web
          image: wordpress:latest
          ports:
            - name: webui
              containerPort: 80
          resources: {}
          tty: true
          env:
            - name: WORDPRESS_DB_HOST
              value: gwdc-db
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - name: nfs-wordpress-html
              mountPath: "/var/www/html/wp-content"
      volumes:
        - name: nfs-wordpress-html
          persistentVolumeClaim:
            claimName: nfs-pvc-app
      restartPolicy: Always
...
