---
# PersistentVolume - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwdc-db
  labels:
    volume: gwdc-db
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 10.8.0.37
    path: "/mnt/sharedfolder/gwdc/db_data"
...
