---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: gwdc
  name: vault-role
  namespace: gwdc
rules:
  - apiGroups:
      - '*'
    resources:
      - secrets
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: meertime
  name: vault-rolebind
  namespace: gwdc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-role
subjects:
  - kind: ServiceAccount
    name: gwdc
    namespace: gwdc
